name: Cache Kernels
on:
  push:
jobs:
  cache:
    runs-on: ubuntu-26.04-arm
    env:
      TMPDIR: /nix/build
    steps:
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: 'cleave'
          witness-carnage: true
          nix-permission-edict: true
      - run: sudo rm -rf /build
      - run: sudo ln -s /nix/build /build
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-26.05
      - uses: cachix/cachix-action@v14
        with:
          name: "1"
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: sudo mkdir -p /nix/build
      - run: sudo chown -R $(whoami):$(whoami) /nix/build
      - run: sudo chmod 755 /nix/build
      - run: df -h && df -i
      - run: nix build --impure --print-build-logs 'path:nix/.#kernels'
        env:
            TMPDIR: /nix/build
      - run: df -h && df -i
        if: always()